export { default as AboutSection } from "./AboutSection/AboutSection";
export { default as ContactSection } from "./ContactSection/ContactSection";
export { default as HeroSection } from "./HeroSection/HeroSection";
export { default as LandingFooter } from "./LandingFooter/LandingFooter";
export { default as LandingNavbar } from "./LandingNavbar/LandingNavbar";
export { default as OrganizationSection } from "./OrganizationSection/OrganizationSection";
export { default as Preloader } from "./Preloader/Preloader";
export { default as ServicesSection } from "./ServicesSection/ServicesSection";
export { default as WisdomSection } from "./WisdomSection/WisdomSection";
